INCLUDE=-I/usr/include -I/usr/local/openresty/luajit/include -I./
LIBDIR=-L/usr/lib64 -L/usr/local/openresty/luajit/lib

CC=gcc
OPTS=-c -fpic -DSYNC_ONLY -ggdb
LOPTS=-shared
LIBS=-llua -lcouchbase

sources:=$(shell find ./ -name "*.c")
objs:=$(patsubst %.c, %.o, $(sources))

%.o: %.c
	$(CC) $(OPTS) $(COPTS) $(INCLUDE) $< -o $@

libcbasesync.so: $(objs)
	$(CC) $(LOPTS) $(LIBDIR) $(LIBS) $(objs) -o $@

clean:
	rm $(shell ls *.o)

all: clean libcbasesync.so

